import React, { useState, useEffect } from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  TouchableOpacity,
  TextInput,
  Share,
  Platform,
  Alert,
} from 'react-native';
import { Stack } from 'expo-router';
import { colors } from '../utils/colors';
import { typography } from '../utils/fonts';
import { useCareRecipientStore } from '../stores/careRecipientStore';
import { useOnboardingStore } from '../stores/onboardingStore';
import { useCircleStore } from '../stores/circleStore';

export default function HealthCardScreen() {
  const { profile, updateProfile, syncToServer, fetchFromServer } = useCareRecipientStore();
  const { caringFor } = useOnboardingStore();
  const { activeCircleId } = useCircleStore();
  const [editing, setEditing] = useState(false);
  const [draft, setDraft] = useState(profile);
  const [newAllergy, setNewAllergy] = useState('');
  const [newCondition, setNewCondition] = useState('');

  useEffect(() => { setDraft(profile); }, [profile]);

  // Fetch from server on mount
  useEffect(() => {
    if (activeCircleId) {
      fetchFromServer(activeCircleId);
    }
  }, [activeCircleId]);

  const name = profile.name || caringFor || 'Care Recipient';

  const handleSave = async () => {
    await updateProfile(draft);
    if (activeCircleId) {
      await syncToServer(activeCircleId);
    }
    setEditing(false);
  };

  const addAllergy = () => {
    if (!newAllergy.trim()) return;
    setDraft({ ...draft, allergies: [...draft.allergies, newAllergy.trim()] });
    setNewAllergy('');
  };

  const removeAllergy = (i: number) => {
    setDraft({ ...draft, allergies: draft.allergies.filter((_, idx) => idx !== i) });
  };

  const addCondition = () => {
    if (!newCondition.trim()) return;
    setDraft({ ...draft, conditions: [...draft.conditions, newCondition.trim()] });
    setNewCondition('');
  };

  const removeCondition = (i: number) => {
    setDraft({ ...draft, conditions: draft.conditions.filter((_, idx) => idx !== i) });
  };

  const handleShare = async () => {
    const card = [
      `EMERGENCY HEALTH CARD`,
      `━━━━━━━━━━━━━━━━━━━━`,
      `Name: ${name}`,
      profile.dateOfBirth ? `DOB: ${profile.dateOfBirth}` : '',
      profile.bloodType ? `Blood Type: ${profile.bloodType}` : '',
      '',
      profile.allergies.length > 0 ? `ALLERGIES:\n${profile.allergies.map(a => `  ⚠️ ${a}`).join('\n')}` : '',
      profile.conditions.length > 0 ? `CONDITIONS:\n${profile.conditions.map(c => `  • ${c}`).join('\n')}` : '',
      '',
      profile.primaryDoctor ? `Doctor: ${profile.primaryDoctor}` : '',
      profile.doctorPhone ? `Doctor Phone: ${profile.doctorPhone}` : '',
      profile.pharmacy ? `Pharmacy: ${profile.pharmacy}` : '',
      profile.pharmacyPhone ? `Pharmacy Phone: ${profile.pharmacyPhone}` : '',
      '',
      profile.insuranceProvider ? `Insurance: ${profile.insuranceProvider}` : '',
      profile.insuranceId ? `ID: ${profile.insuranceId}` : '',
      '',
      profile.emergencyContacts.length > 0
        ? `EMERGENCY CONTACTS:\n${profile.emergencyContacts.map(c => `  ${c.name} (${c.relation}): ${c.phone}`).join('\n')}`
        : '',
      profile.notes ? `\nNotes: ${profile.notes}` : '',
      '',
      `Generated by Careo`,
    ].filter(Boolean).join('\n');

    try {
      await Share.share({ message: card, title: `${name} — Emergency Health Card` });
    } catch (err) {
      // Share was cancelled or failed — no action needed
    }
  };

  // ─── View Mode ───
  if (!editing) {
    const isEmpty = !profile.name && profile.allergies.length === 0 && profile.conditions.length === 0;

    return (
      <>
        <Stack.Screen options={{ title: '', headerShown: true }} />
        <ScrollView style={styles.root} contentContainerStyle={styles.scrollContent}>

          {/* Hero */}
          <View style={styles.hero}>
            <Text style={styles.heroEmoji}>🏥</Text>
            <Text style={styles.heroTitle}>Emergency{'\n'}Health Card</Text>
            <Text style={styles.heroSub}>
              {isEmpty
                ? `Set up ${caringFor}'s health profile.\nReady in 2 minutes.`
                : `${name}'s critical health info.\nShare instantly in an emergency.`}
            </Text>
          </View>

          {isEmpty ? (
            <View style={styles.emptyState}>
              <Text style={styles.emptyEmoji}>📋</Text>
              <Text style={styles.emptyTitle}>No health info yet</Text>
              <Text style={styles.emptyText}>
                When you rush to the ER at 2am, you need allergies, medications, and doctor info instantly.
              </Text>
              <TouchableOpacity style={styles.primaryBtn} onPress={() => { setDraft({ ...profile, name: caringFor !== 'your loved one' ? caringFor : '' }); setEditing(true); }} accessibilityRole="button" accessibilityLabel="Set up health card">
                <Text style={styles.primaryBtnText}>Set up health card</Text>
              </TouchableOpacity>
            </View>
          ) : (
            <>
              {/* Card */}
              <View style={styles.card}>
                <View style={styles.cardHeader}>
                  <Text style={styles.cardName}>{name}</Text>
                  {profile.bloodType ? (
                    <View style={styles.bloodBadge}>
                      <Text style={styles.bloodText}>{profile.bloodType}</Text>
                    </View>
                  ) : null}
                </View>
                {profile.dateOfBirth ? <Text style={styles.cardDob}>DOB: {profile.dateOfBirth}</Text> : null}

                {/* Allergies */}
                {profile.allergies.length > 0 && (
                  <View style={styles.cardSection}>
                    <Text style={styles.cardSectionTitle}>⚠️ ALLERGIES</Text>
                    <View style={styles.tagRow}>
                      {profile.allergies.map((a, i) => (
                        <View key={i} style={styles.allergyTag}>
                          <Text style={styles.allergyText}>{a}</Text>
                        </View>
                      ))}
                    </View>
                  </View>
                )}

                {/* Conditions */}
                {profile.conditions.length > 0 && (
                  <View style={styles.cardSection}>
                    <Text style={styles.cardSectionTitle}>CONDITIONS</Text>
                    {profile.conditions.map((c, i) => (
                      <Text key={i} style={styles.conditionText}>• {c}</Text>
                    ))}
                  </View>
                )}

                {/* Doctors & Pharmacy */}
                {(profile.primaryDoctor || profile.pharmacy) && (
                  <View style={styles.cardSection}>
                    <Text style={styles.cardSectionTitle}>CARE TEAM</Text>
                    {profile.primaryDoctor && (
                      <View style={styles.contactRow}>
                        <Text style={styles.contactIcon}>🩺</Text>
                        <View>
                          <Text style={styles.contactName}>{profile.primaryDoctor}</Text>
                          {profile.doctorPhone && <Text style={styles.contactPhone}>{profile.doctorPhone}</Text>}
                        </View>
                      </View>
                    )}
                    {profile.pharmacy && (
                      <View style={styles.contactRow}>
                        <Text style={styles.contactIcon}>💊</Text>
                        <View>
                          <Text style={styles.contactName}>{profile.pharmacy}</Text>
                          {profile.pharmacyPhone && <Text style={styles.contactPhone}>{profile.pharmacyPhone}</Text>}
                        </View>
                      </View>
                    )}
                  </View>
                )}

                {/* Insurance */}
                {profile.insuranceProvider && (
                  <View style={styles.cardSection}>
                    <Text style={styles.cardSectionTitle}>INSURANCE</Text>
                    <Text style={styles.insuranceName}>{profile.insuranceProvider}</Text>
                    {profile.insuranceId && <Text style={styles.insuranceId}>ID: {profile.insuranceId}</Text>}
                  </View>
                )}

                {/* Emergency Contacts */}
                {profile.emergencyContacts.length > 0 && (
                  <View style={styles.cardSection}>
                    <Text style={styles.cardSectionTitle}>EMERGENCY CONTACTS</Text>
                    {profile.emergencyContacts.map((c, i) => (
                      <View key={i} style={styles.contactRow}>
                        <Text style={styles.contactIcon}>📞</Text>
                        <View>
                          <Text style={styles.contactName}>{c.name} ({c.relation})</Text>
                          <Text style={styles.contactPhone}>{c.phone}</Text>
                        </View>
                      </View>
                    ))}
                  </View>
                )}

                {profile.notes ? (
                  <View style={styles.cardSection}>
                    <Text style={styles.cardSectionTitle}>NOTES</Text>
                    <Text style={styles.notesText}>{profile.notes}</Text>
                  </View>
                ) : null}
              </View>

              {/* Actions */}
              <View style={styles.actions}>
                <TouchableOpacity style={styles.shareBtn} onPress={handleShare} accessibilityRole="button" accessibilityLabel="Share health card">
                  <Text style={styles.shareBtnEmoji}>📤</Text>
                  <Text style={styles.shareBtnText}>Share health card</Text>
                </TouchableOpacity>
                <TouchableOpacity style={styles.editBtn} onPress={() => setEditing(true)} accessibilityRole="button" accessibilityLabel="Edit info">
                  <Text style={styles.editBtnText}>Edit info</Text>
                </TouchableOpacity>
              </View>
            </>
          )}

          <View style={{ height: 40 }} />
        </ScrollView>
      </>
    );
  }

  // ─── Edit Mode ───
  return (
    <>
      <Stack.Screen options={{ title: 'Edit Health Card', headerShown: true }} />
      <ScrollView style={styles.root} contentContainerStyle={styles.editContent} keyboardShouldPersistTaps="handled">

        <Field label="Full Name" value={draft.name} onChangeText={(v) => setDraft({ ...draft, name: v })} placeholder={caringFor} />
        <Field label="Date of Birth" value={draft.dateOfBirth} onChangeText={(v) => setDraft({ ...draft, dateOfBirth: v })} placeholder="MM/DD/YYYY" />
        <Field label="Blood Type" value={draft.bloodType} onChangeText={(v) => setDraft({ ...draft, bloodType: v })} placeholder="e.g. A+, O-" />

        {/* Allergies */}
        <Text style={styles.fieldLabel}>Allergies</Text>
        <View style={styles.tagRow}>
          {draft.allergies.map((a, i) => (
            <TouchableOpacity key={i} style={styles.allergyTagEdit} onPress={() => removeAllergy(i)}>
              <Text style={styles.allergyText}>{a} ✕</Text>
            </TouchableOpacity>
          ))}
        </View>
        <View style={styles.addRow}>
          <TextInput style={styles.addInput} value={newAllergy} onChangeText={setNewAllergy} placeholder="Add allergy" placeholderTextColor={colors.textHint} onSubmitEditing={addAllergy} />
          <TouchableOpacity style={styles.addBtn} onPress={addAllergy}><Text style={styles.addBtnText}>+</Text></TouchableOpacity>
        </View>

        {/* Conditions */}
        <Text style={styles.fieldLabel}>Conditions</Text>
        <View style={styles.tagRow}>
          {draft.conditions.map((c, i) => (
            <TouchableOpacity key={i} style={styles.conditionTagEdit} onPress={() => removeCondition(i)}>
              <Text style={styles.conditionTagText}>{c} ✕</Text>
            </TouchableOpacity>
          ))}
        </View>
        <View style={styles.addRow}>
          <TextInput style={styles.addInput} value={newCondition} onChangeText={setNewCondition} placeholder="Add condition" placeholderTextColor={colors.textHint} onSubmitEditing={addCondition} />
          <TouchableOpacity style={styles.addBtn} onPress={addCondition}><Text style={styles.addBtnText}>+</Text></TouchableOpacity>
        </View>

        <Field label="Primary Doctor" value={draft.primaryDoctor} onChangeText={(v) => setDraft({ ...draft, primaryDoctor: v })} placeholder="Dr. Smith" />
        <Field label="Doctor Phone" value={draft.doctorPhone} onChangeText={(v) => setDraft({ ...draft, doctorPhone: v })} placeholder="(555) 123-4567" keyboardType="phone-pad" />
        <Field label="Pharmacy" value={draft.pharmacy} onChangeText={(v) => setDraft({ ...draft, pharmacy: v })} placeholder="CVS Main St" />
        <Field label="Pharmacy Phone" value={draft.pharmacyPhone} onChangeText={(v) => setDraft({ ...draft, pharmacyPhone: v })} placeholder="(555) 987-6543" keyboardType="phone-pad" />
        <Field label="Insurance Provider" value={draft.insuranceProvider} onChangeText={(v) => setDraft({ ...draft, insuranceProvider: v })} placeholder="Blue Cross" />
        <Field label="Insurance ID" value={draft.insuranceId} onChangeText={(v) => setDraft({ ...draft, insuranceId: v })} placeholder="XYZ123456" />
        <Field label="Notes" value={draft.notes} onChangeText={(v) => setDraft({ ...draft, notes: v })} placeholder="Important details for doctors..." multiline />

        <TouchableOpacity style={styles.primaryBtn} onPress={handleSave} accessibilityRole="button" accessibilityLabel="Save health card">
          <Text style={styles.primaryBtnText}>Save health card</Text>
        </TouchableOpacity>

        <TouchableOpacity style={styles.cancelBtn} onPress={() => { setDraft(profile); setEditing(false); }} accessibilityRole="button" accessibilityLabel="Cancel">
          <Text style={styles.cancelBtnText}>Cancel</Text>
        </TouchableOpacity>

        <View style={{ height: 40 }} />
      </ScrollView>
    </>
  );
}

// ─── Field Component ────────────────────────────────────────────────

function Field({ label, value, onChangeText, placeholder, multiline, keyboardType }: {
  label: string; value: string; onChangeText: (v: string) => void; placeholder?: string; multiline?: boolean; keyboardType?: any;
}) {
  return (
    <View style={styles.fieldWrap}>
      <Text style={styles.fieldLabel}>{label}</Text>
      <TextInput
        style={[styles.fieldInput, multiline && { height: 80, textAlignVertical: 'top' }]}
        value={value}
        onChangeText={onChangeText}
        placeholder={placeholder}
        placeholderTextColor={colors.textHint}
        multiline={multiline}
        keyboardType={keyboardType}
      />
    </View>
  );
}

// ─── Styles ─────────────────────────────────────────────────────────

const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: colors.bg },
  scrollContent: { paddingBottom: 20 },
  editContent: { paddingHorizontal: 20, paddingTop: 16 },

  // Hero
  hero: {
    backgroundColor: colors.heroStart,
    paddingTop: 20,
    paddingBottom: 28,
    paddingHorizontal: 24,
    alignItems: 'center',
  },
  heroEmoji: { fontSize: 48, marginBottom: 12 },
  heroTitle: { ...typography.displayMedium, color: '#fff', textAlign: 'center' },
  heroSub: { ...typography.bodyMedium, color: 'rgba(255,255,255,0.7)', textAlign: 'center', marginTop: 8, lineHeight: 22 },

  // Empty
  emptyState: { alignItems: 'center', padding: 32, paddingTop: 48 },
  emptyEmoji: { fontSize: 48, marginBottom: 16, opacity: 0.5 },
  emptyTitle: { ...typography.headingLarge, color: colors.textPrimary, marginBottom: 8 },
  emptyText: { ...typography.bodyMedium, color: colors.textHint, textAlign: 'center', lineHeight: 22, marginBottom: 28 },

  // Card
  card: {
    marginHorizontal: 18,
    marginTop: 20,
    backgroundColor: '#fff',
    borderRadius: 20,
    padding: 22,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 12,
    elevation: 4,
    borderTopWidth: 4,
    borderTopColor: colors.danger,
  },
  cardHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 4 },
  cardName: { ...typography.displaySmall, color: colors.textPrimary },
  bloodBadge: { backgroundColor: colors.tintEmergency, paddingHorizontal: 10, paddingVertical: 4, borderRadius: 8 },
  bloodText: { ...typography.labelMedium, color: colors.danger, fontWeight: '700' },
  cardDob: { ...typography.bodySmall, color: colors.textHint, marginBottom: 16 },

  cardSection: { marginTop: 18, paddingTop: 16, borderTopWidth: 1, borderTopColor: colors.divider },
  cardSectionTitle: { ...typography.labelSmall, color: colors.textHint, letterSpacing: 1.5, fontWeight: '700', marginBottom: 10 },

  tagRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginBottom: 4 },
  allergyTag: { backgroundColor: '#FEE2E2', paddingHorizontal: 12, paddingVertical: 6, borderRadius: 10 },
  allergyText: { ...typography.labelSmall, color: colors.danger, fontWeight: '600' },

  conditionText: { ...typography.bodyMedium, color: colors.textPrimary, marginBottom: 4 },

  contactRow: { flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 10 },
  contactIcon: { fontSize: 20 },
  contactName: { ...typography.headingSmall, color: colors.textPrimary },
  contactPhone: { ...typography.bodySmall, color: colors.primary },

  insuranceName: { ...typography.headingSmall, color: colors.textPrimary },
  insuranceId: { ...typography.bodySmall, color: colors.textSecondary, marginTop: 2 },

  notesText: { ...typography.bodyMedium, color: colors.textSecondary, lineHeight: 22 },

  // Actions
  actions: { paddingHorizontal: 18, marginTop: 20, gap: 10 },
  shareBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    backgroundColor: colors.accent,
    paddingVertical: 18,
    borderRadius: 16,
    shadowColor: colors.accent,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 10,
    elevation: 4,
  },
  shareBtnEmoji: { fontSize: 18 },
  shareBtnText: { ...typography.button, color: '#fff', fontSize: 17 },
  editBtn: {
    alignItems: 'center',
    paddingVertical: 14,
    backgroundColor: '#fff',
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: colors.border,
  },
  editBtnText: { ...typography.button, color: colors.textSecondary },

  // Edit form
  fieldWrap: { marginBottom: 16 },
  fieldLabel: { ...typography.labelMedium, color: colors.textSecondary, marginBottom: 6 },
  fieldInput: {
    ...typography.bodyLarge,
    backgroundColor: '#fff',
    borderWidth: 1.5,
    borderColor: colors.border,
    borderRadius: 14,
    paddingVertical: 14,
    paddingHorizontal: 16,
    color: colors.textPrimary,
  },

  addRow: { flexDirection: 'row', gap: 8, marginBottom: 16 },
  addInput: {
    ...typography.bodyMedium,
    flex: 1,
    backgroundColor: '#fff',
    borderWidth: 1.5,
    borderColor: colors.border,
    borderRadius: 14,
    paddingVertical: 12,
    paddingHorizontal: 16,
    color: colors.textPrimary,
  },
  addBtn: {
    width: 44,
    height: 44,
    borderRadius: 14,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  addBtnText: { color: '#fff', fontSize: 22, fontWeight: '600' },

  allergyTagEdit: { backgroundColor: '#FEE2E2', paddingHorizontal: 12, paddingVertical: 6, borderRadius: 10 },
  conditionTagEdit: { backgroundColor: colors.tintTask, paddingHorizontal: 12, paddingVertical: 6, borderRadius: 10 },
  conditionTagText: { ...typography.labelSmall, color: colors.primary, fontWeight: '600' },

  primaryBtn: {
    backgroundColor: colors.primary,
    paddingVertical: 18,
    borderRadius: 16,
    alignItems: 'center',
    marginTop: 8,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 10,
    elevation: 4,
  },
  primaryBtnText: { ...typography.button, color: '#fff', fontSize: 17 },
  cancelBtn: { alignItems: 'center', paddingVertical: 14, marginTop: 8 },
  cancelBtnText: { ...typography.labelLarge, color: colors.textHint },
});
